name: Soil Data CI/CD
on: [push]
jobs:
  data-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas

      - name: Validate CSV Columns
        run: |
          python -c "import pandas as pd; df=pd.read_csv('Crop_recommendation.csv'); required=['N','P','K','ph']; assert all(col in df.columns for col in required)"
          echo "CI/CD: Data Schema Validated Successfully!"
